#cloud-config

runcmd:
  - |
    curl -L https://github.com/elitak/nixos-infect/raw/master/nixos-infect | NIX_CHANNEL=nixos-25.11 bash -x 2>&1 | tee /var/log/nixos-infect.log
    # After reboot, run: nixos-rebuild switch --flake github:user/repo#default
